export const SET_INITIAL_NEWS_DATA = "SET_INITIAL_NEWS_DATA";
export const SAVE_NEW_NEWS = "SAVE_NEW_NEWS";
export const SAVE_UPDATED_NEWS = "SAVE_UPDATED_NEWS";
export const SAVE_NEW_COMMENT = "SAVE_NEW_COMMENT";
