export const SET_AUTH_FORM_OPENED = "SET_AUTH_FORM_OPENED";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_INITIAL_AUTH_DATA = "SET_INITIAL_AUTH_DATA";
export const SET_REGISTERED_USER = "SET_REGISTERED_USER";
